# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL loglar? (geli?tirme i?in)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# ===============================
# LOGGING (opsiyonel ama faydal?)
# ===============================
# application.properties
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.access=DEBUG
logging.level.com.murdergame=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.output.ansi.enabled=ALWAYS

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-hours=8